import type { Metadata } from "next";

import { Anek_Bangla } from "next/font/google";

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Marquee from "@/components/Marquee";
import { ToastContainer } from "react-toastify";

const anekBangla = Anek_Bangla({
    subsets: ["latin", "bengali"],
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${anekBangla.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <Marquee />
        <ToastContainer />
        {children}
        <Footer />
        
        
        </body>
    </html>
  );
}
